### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Elhambasir** [CaptainBawa/ScoreTracker#5]
Good job so far your code is clean, readable, and well-prepared. There is one thing I kindly suggest to you try to put a brief comment about your function and code.

**Comment by AbenezerAssefa** [comment]
Hi @CaptainBawa 👋👋👋, 

![StandingOvationGIF (4)](https://user-images.githubusercontent.com/64643995/231992738-1cc6b090-3b07-4084-b07d-c878bbe08d90.gif)


Good Job so far!  I would like to bring to your attention that there is a slight issue with the demo submit and refresh button not functioning properly. Please make the necessary corrections to ensure that these buttons are working correctly.

## Highlights✅✅

- [x] Linters are correctly set up and they are passing👍.
- [x] All test cases are passing👍.
- [x] Tests are grouped using the description() method👍.
- [x] GitHub flow practice has been used👍.

## Optional suggestions
- [OPTIONAL] Currently, the only way to add to your project is to hit the enter key👍 But we can make it better by ensuring the `enter` icon works properly as this will better the user's experience👍.

Cheers, and Happy coding!👏👏👏

**Comment by Jawad-Nazari** [comment]
Hi @CaptainBawa ,

Well done on your work, Your code is readable and functional just there is a suggestion from my side that I noticed you have used a long description to describe the functionality of your code. It will be great if you provide it with a shorter comment. 👏
